// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressBook.proto

package cc.protobuf.model;

public final class AddressBookProtos {
  private AddressBookProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cc_protobuf_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cc_protobuf_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cc_protobuf_Person_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cc_protobuf_Person_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cc_protobuf_Person_AddressBook_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cc_protobuf_Person_AddressBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021addressBook.proto\022\013cc.protobuf\"\216\002\n\006Per" +
      "son\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005emial\030\003" +
      " \001(\t\022.\n\005phone\030\004 \003(\0132\037.cc.protobuf.Person" +
      ".PhoneNumber\032J\n\013PhoneNumber\022\016\n\006number\030\001 " +
      "\001(\t\022+\n\004rtpe\030\002 \001(\0162\035.cc.protobuf.Person.P" +
      "honeType\0322\n\013AddressBook\022#\n\006people\030\004 \003(\0132" +
      "\023.cc.protobuf.Person\"+\n\tPhoneType\022\n\n\006MOB" +
      "ILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\003B(\n\021cc.protobuf" +
      ".modelB\021AddressBookProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cc_protobuf_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cc_protobuf_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cc_protobuf_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Emial", "Phone", });
    internal_static_cc_protobuf_Person_PhoneNumber_descriptor =
      internal_static_cc_protobuf_Person_descriptor.getNestedTypes().get(0);
    internal_static_cc_protobuf_Person_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cc_protobuf_Person_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Rtpe", });
    internal_static_cc_protobuf_Person_AddressBook_descriptor =
      internal_static_cc_protobuf_Person_descriptor.getNestedTypes().get(1);
    internal_static_cc_protobuf_Person_AddressBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cc_protobuf_Person_AddressBook_descriptor,
        new java.lang.String[] { "People", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
