// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressBook.proto

package cc.protobuf.model;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cc.protobuf.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>string emial = 3;</code>
   */
  java.lang.String getEmial();
  /**
   * <code>string emial = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmialBytes();

  /**
   * <code>repeated .cc.protobuf.Person.PhoneNumber phone = 4;</code>
   */
  java.util.List<cc.protobuf.model.Person.PhoneNumber> 
      getPhoneList();
  /**
   * <code>repeated .cc.protobuf.Person.PhoneNumber phone = 4;</code>
   */
  cc.protobuf.model.Person.PhoneNumber getPhone(int index);
  /**
   * <code>repeated .cc.protobuf.Person.PhoneNumber phone = 4;</code>
   */
  int getPhoneCount();
  /**
   * <code>repeated .cc.protobuf.Person.PhoneNumber phone = 4;</code>
   */
  java.util.List<? extends cc.protobuf.model.Person.PhoneNumberOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <code>repeated .cc.protobuf.Person.PhoneNumber phone = 4;</code>
   */
  cc.protobuf.model.Person.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index);
}
